version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./app/public:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports : 
      - "8080:80"
  fpm:
    image: php:8-fpm
    volumes:
      - ./app/public:/var/www/html